spring.application.name=gateway-api
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=cliente-api
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/clientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=vendas-api
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/vendas/**

spring.cloud.gateway.server.webmvc.routes[2].id=produto-api
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/produtos/**